# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.synced_folder "../../", "/home/vagrant/ansible-mesos-playbook"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  # ubuntu
  config.vm.define 'mesos-single-node', primary: true do |c|
    c.vm.network "private_network", ip: "192.168.100.2"
    config.vm.hostname = "mesos-single-node.local"
    c.vm.box = "ubuntu/trusty64"
    c.vm.provision "shell" do |s|
      s.inline = "apt-get update -y; apt-get install ansible -y;"
      s.privileged = true
    end
    c.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../playbook.yml"
        ansible.inventory_path = "hosts"
        ansible.verbose = 'v'
    end
  end


  # centos:
  # config.vm.define 'centos' do |c|
  #   c.vm.network "private_network", ip: "192.168.100.3"
  #   c.vm.box = "chef/centos-6.5"
  #   c.vm.provision "shell" do |s|
  #     s.inline = "/bin/true"
      # s.privileged = true
    # end
  # end

end
